# Generated by Django 5.0.4 on 2024-05-07 18:39

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='coursatty-favicon-black.png', null=True, upload_to=courses.models.imagesave),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='coursatty-high-resolution-logo-white.png', null=True, upload_to=courses.models.imagesave),
        ),
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(default='coursatty-favicon-black.png', null=True, upload_to=courses.models.imagesave),
        ),
    ]
