# Generated by Django 5.0.4 on 2024-05-10 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_category_image_alter_course_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.industry'),
        ),
    ]
