import SideNav from "@/Components/Shared/SideNav";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Coursatty",
  description: "Generated by bo_0dy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div 
      className="grid lg:grid-cols-5 grid-cols-1 pt-[64px]"
    >
      <SideNav className={'lg:col-span-1 lg:flex hidden mt-[50px] justify-center'}  />
      <div className=" col-span-4 py-2 lg:pr-8">
        <div className="bg-white rounded-md min-h-full shadow-lg">
          {children}
        </div>
      </div>
    </div>
  );
}
