import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from '@/redux';
import { Nav } from "@/Components/Shared";
import { Setup } from "@/Components/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coursatty",
  description: "Generated by bo_0dy",
  icons:{
    icon:'/coursatty-favicon-color.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className + " bg-gray-100"}>
          <Provider>
          <Setup />
          <Nav />
            {children}
          </Provider>
        </body>
    </html>
  );
}
