# Generated by Django 5.0.4 on 2024-05-07 13:07

import django.db.models.deletion
import home.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(default='Banner/default.webp', null=True, upload_to=home.models.imagesave)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.banner')),
            ],
        ),
    ]
