# Generated by Django 5.0.4 on 2024-05-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_created_by_bannerimage_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
