# Generated by Django 5.0.4 on 2024-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_bannerimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
