import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Coursatty",
  description: "Generated by bo_0dy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
        {children}
    </div>
  );
}
